config/routes.rb
Toolman::Application.routes.draw do

  resources :data_injections, :only => [:create, :new, :index, :show]

  resources :combination_tools

  resources :service_stock_orders, :except => [:new] do
    collection do
      get :new_in
      get :new_out
    end
  end

  resources :barcode_generators

  resources :tool_cards

  resources :quality_categories

  resources :quality_deviation_reports do
    member do
      put :confirm
    end
  end

  resources :scrap_orders do
  resources :items, :controller => :scrap_order_items
    member do
      put :confirm
    end
  end

  resources :scrap_types

  resources :tunning_work_orders do
    member do
      put :confirm
    end
    # resources :setting_items, :controller => :tunning_work_order_setting_items
    # resources :sharpen_items, :controller => :tunning_work_order_sharpen_items
  end

  resources :sharpen_devices

  resources :setting_types

  resources :setting_devices

  resources :assembly_tools do
    member do
      put :confirm
    end
    resources :items, :controller => :assembly_tool_items
    resources :tunning_work_orders
  end

  resources :tool_materials do
    member do
      get :print
    end
    resources :serving_parts do
      collection do 
        post :mass_create
        post :print
      end
    end
  end

  resources :agencies

  resources :manufacturers

  resources :sub_categories

  resources :workshop_processes

  resources :product_lines

  resources :engine_models
  
  resources :categories
  
  resources :facility_types
  
  resources :facility_codes

##############################################
  authenticated :user do
    root :to => 'home#index'
  end

  devise_for :users do
    root :to => 'devise/sessions#new'
  end
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users, :only => [:show, :index]
##############################################

end

app/models/tunning_work_order_setting_item.rb
class TunningWorkOrderSettingItem < TunningWorkOrderItem
  belongs_to :tunning_work_order
  belongs_to :setting_type, :class_name => :SettingType, :foreign_key => :operation_type_id
  belongs_to :setting_device, :class_name => :SettingDevice, :foreign_key => :operation_device_id
  belongs_to :operator, :class_name => :User, :foreign_key => :operator_id
  attr_accessible :actual_time, :expected_time, :operation_device_id, :operation_type_id, :operator_id
end

app/controllers/tunning_work_order_setting_items_controller.rb
class TunningWorkOrderSettingItemsController < ApplicationController
  before_filter :find_tunning_work_order
  
  # GET /tunning_work_order_setting_items
  # GET /tunning_work_order_setting_items.json
  def index
    @tunning_work_order_setting_items = @tunning_work_order.setting_item ? [@tunning_work_order.setting_item,] : []

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tunning_work_order_setting_items }
    end
  end

  # GET /tunning_work_order_setting_items/1
  # GET /tunning_work_order_setting_items/1.json
  def show
    @tunning_work_order_setting_item = @tunning_work_order.setting_item if @tunning_work_order.setting_item.id == params[:id].to_i

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tunning_work_order_setting_item }
    end
  end

  # GET /tunning_work_order_setting_items/new
  # GET /tunning_work_order_setting_items/new.json
  def new
    @tunning_work_order_setting_item = @tunning_work_order.setting_item
    if @tunning_work_order_setting_item
      respond_to do |format|
        format.html { redirect_to tunning_work_order_setting_items_url(@tunning_work_order), notice: 'Already have a setting item' }
      end
      return
    end
    @tunning_work_order_setting_item = @tunning_work_order.build_setting_item
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tunning_work_order_setting_item }
    end
  end

  # GET /tunning_work_order_setting_items/1/edit
  def edit
    # @tunning_work_order_setting_item = TunningWorkOrderSettingItem.find(params[:id])
    @tunning_work_order_setting_item = @tunning_work_order.setting_item if @tunning_work_order.setting_item.id == params[:id].to_i
  end

  # POST /tunning_work_order_setting_items
  # POST /tunning_work_order_setting_items.json
  def create
    @tunning_work_order_setting_item = TunningWorkOrderSettingItem.new(params[:tunning_work_order_setting_item])

    respond_to do |format|
      if @tunning_work_order_setting_item.save
        format.html { redirect_to @tunning_work_order_setting_item, notice: 'Tunning work order setting item was successfully created.' }
        format.json { render json: @tunning_work_order_setting_item, status: :created, location: @tunning_work_order_setting_item }
      else
        format.html { render action: "new" }
        format.json { render json: @tunning_work_order_setting_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tunning_work_order_setting_items/1
  # PUT /tunning_work_order_setting_items/1.json
  def update
    @tunning_work_order_setting_item = TunningWorkOrderSettingItem.find(params[:id])

    respond_to do |format|
      if @tunning_work_order_setting_item.update_attributes(params[:tunning_work_order_setting_item])
        format.html { redirect_to @tunning_work_order_setting_item, notice: 'Tunning work order setting item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tunning_work_order_setting_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tunning_work_order_setting_items/1
  # DELETE /tunning_work_order_setting_items/1.json
  def destroy
    @tunning_work_order_setting_item = TunningWorkOrderSettingItem.find(params[:id])
    @tunning_work_order_setting_item.destroy

    respond_to do |format|
      format.html { redirect_to tunning_work_order_setting_items_url }
      format.json { head :no_content }
    end
  end

  protected
  
  def find_tunning_work_order
    @tunning_work_order = TunningWorkOrder.find(params[:tunning_work_order_id])
  end
end

app/helpers/tunning_work_order_setting_items_helper.rb
module TunningWorkOrderSettingItemsHelper
end

app/views/tunning_work_order_setting_items/_form.html.erb
<%= simple_form_for(@tunning_work_order_setting_item, :url => tunning_work_order_setting_item_path(@tunning_work_order, @tunning_work_order_setting_item)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :setting_device %>
    <%= f.association :setting_type %>
    <%= f.input :expected_time, :readonly => true %>
    <%= f.input :actual_time %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tunning_work_order_setting_items/edit.html.erb
<% content_for :breadcrumb do %>
  <li><%= link_to t('views.home.title', default: 'Home'), root_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%= link_to t('tunning_work_orders.index.title'), tunning_work_orders_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%= link_to t('tunning_work_order_setting_items.index.title'), tunning_work_order_setting_items_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%= t('.title') %></li>
<% end %>
<h1><%=t '.title'%></h1>

<%= render 'form' %>

<%= link_to t('helpers.links.show'), @tunning_work_order_setting_item, class: 'btn-show' %>
<%= link_to t('helpers.links.back'), tunning_work_order_setting_items_path(@tunning_work_order), class: 'btn-back' %>

app/views/tunning_work_order_setting_items/index.html.erb
<%- model_class = TunningWorkOrderSettingItem.new.class -%>
<% content_for :breadcrumb do %>
  <li><%= link_to t('views.home.title', default: 'Home'), root_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%= link_to t('tunning_work_orders.index.title'), tunning_work_orders_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%=t '.title', default: model_class.model_name.human.pluralize %></li>
<% end %>
<h1><%=t '.title', default: model_class.model_name.human.pluralize %></h1>

<div class='operation-group'>
  <div class='action-group'>
    <%= link_to t('.new', default: t('helpers.links.new')), new_tunning_work_order_setting_item_path, class: 'btn-new' %>    
  </div>
</div>

<table class='table-listed'>
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:setting_device) %></th>
      <th><%= model_class.human_attribute_name(:setting_type) %></th>
      <th><%= model_class.human_attribute_name(:operator) %></th>
      <th><%= model_class.human_attribute_name(:actual_time) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= t('.actions', default: t('helpers.actions')) %></th>
    </tr>
  </thead>
  <tbody>
    <% @tunning_work_order_setting_items.each do |tunning_work_order_setting_item| %>
      <tr>
        <td><%= tunning_work_order_setting_item.setting_device %></td>
        <td><%= tunning_work_order_setting_item.setting_type %></td>
        <td><%= tunning_work_order_setting_item.operator %></td>
        <td><%= tunning_work_order_setting_item.actual_time %></td>
        <td><%= l(tunning_work_order_setting_item.created_at) %></td>
        <td><div class='btn-group'>
          <%= link_to t('.show', default: t('helpers.links.show')), tunning_work_order_setting_item_path(@tunning_work_order, tunning_work_order_setting_item), class: 'btn-show' %>
          <%= link_to t('.edit', default: t('helpers.links.edit')), edit_tunning_work_order_setting_item_path(@tunning_work_order, tunning_work_order_setting_item), class: 'btn-edit' %>
          <%= link_to t('.destroy', default: t('helpers.links.destroy')), tunning_work_order_setting_item_path(@tunning_work_order, tunning_work_order_setting_item), confirm: t('.confirm', default: t('helpers.links.destroy_confirm', default: 'Are you sure?')), method: :delete, class: 'btn-destroy' %>
      </div></td>
        </td>
      </tr>
    <% end %>
  </tbody>  
</table>

app/views/tunning_work_order_setting_items/new.html.erb
<h1>New tunning_work_order_setting_item</h1>

<%= render 'form' %>

<%= link_to 'Back', tunning_work_order_setting_items_path %>

app/views/tunning_work_order_setting_items/show.html.erb
<% content_for :breadcrumb do %>
  <li><%= link_to t('views.home.title', default: 'Home'), root_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%= link_to t('tunning_work_orders.index.title'), tunning_work_orders_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%= link_to t('tunning_work_order_setting_items.index.title'), tunning_work_order_setting_items_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%= t('.title') %></li>
<% end %>
<h1><%= t('.title') %></h1>
<p><b><%= @tunning_work_order_setting_item.class.human_attribute_name(:setting_device) %>:</b>
  <%= @tunning_work_order_setting_item.setting_device %>
</p>

<p><b><%= @tunning_work_order_setting_item.class.human_attribute_name(:setting_type) %>:</b>
  <%= @tunning_work_order_setting_item.setting_type %>
</p>

<p><b><%= @tunning_work_order_setting_item.class.human_attribute_name(:expected_time) %>:</b>
  <%= @tunning_work_order_setting_item.expected_time %>
</p>

<p><b><%= @tunning_work_order_setting_item.class.human_attribute_name(:actual_time) %>:</b>
  <%= @tunning_work_order_setting_item.actual_time %>
</p>

<%= link_to t('helpers.links.edit'), edit_tunning_work_order_setting_item_path(@tunning_work_order_setting_item), class: 'btn-edit' %>
<%= link_to t('helpers.links.back'), tunning_work_order_setting_items_path, class: 'btn-back' %>