config/routes.rb
Toolman::Application.routes.draw do

  resources :data_injections, :only => [:create, :new, :index, :show]

  resources :combination_tools

  resources :service_stock_orders, :except => [:new] do
    collection do
      get :new_in
      get :new_out
    end
  end

  resources :barcode_generators

  resources :tool_cards

  resources :quality_categories

  resources :quality_deviation_reports do
    member do
      put :confirm
    end
  end

  resources :scrap_orders do
  resources :items, :controller => :scrap_order_items
    member do
      put :confirm
    end
  end

  resources :scrap_types

  resources :tunning_work_orders do
    member do
      put :confirm
    end
    # resources :setting_items, :controller => :tunning_work_order_setting_items
    # resources :sharpen_items, :controller => :tunning_work_order_sharpen_items
  end

  resources :sharpen_devices

  resources :setting_types

  resources :setting_devices

  resources :assembly_tools do
    member do
      put :confirm
    end
    resources :items, :controller => :assembly_tool_items
    resources :tunning_work_orders
  end

  resources :tool_materials do
    member do
      get :print
    end
    resources :serving_parts do
      collection do 
        post :mass_create
        post :print
      end
    end
  end

  resources :agencies

  resources :manufacturers

  resources :sub_categories

  resources :workshop_processes

  resources :product_lines

  resources :engine_models
  
  resources :categories
  
  resources :facility_types
  
  resources :facility_codes

##############################################
  authenticated :user do
    root :to => 'home#index'
  end

  devise_for :users do
    root :to => 'devise/sessions#new'
  end
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users, :only => [:show, :index]
##############################################

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% content_for :breadcrumb do %>
  <li><%= t('views.home.title', default: 'Home') %></li>
<% end %>

<table class='table-menued'>
  <thead>
    <tr>
      <th colspan='5'><%= t('.quality.title', default: 'Quality Maintenance') %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= link_to t('.quality.quality_deviation_report', default: 'Quality Deviation Report'), quality_deviation_reports_path %></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

<table class='table-menued'>
  <thead>
    <tr>
      <th colspan='5'><%= t('.logistic.title', default: 'Logistic') %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= link_to t('.logistic.in_out', default: 'In & Out'), service_stock_orders_path %></td>
      <td><%= link_to t('.logistic.in', default: 'In'), new_in_service_stock_orders_path %></td>
      <td><%= link_to t('.logistic.out', default: 'Out'), new_out_service_stock_orders_path %></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

<table class='table-menued'>
  <thead>
    <tr>
      <th colspan='5'><%= t('.sharpen.title', default: 'Sharpening Maintenance') %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= link_to t('.sharpen.tunning_work_order', default: 'Tunning Work Order'), tunning_work_orders_path %></td>
      <td><%= link_to t('.sharpen.scrap', default: 'Scrap'), scrap_orders_path %></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

<table class='table-menued'>
  <thead>
    <tr>
      <th colspan='5'><%= t('.tool_management.title', default: 'Tool Management') %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= link_to t('.tool_management.tool_material', default: 'Tool Material'), tool_materials_path %></td>
      <td><%= link_to t('.tool_management.assembly_tool', default: 'Assmebly Tool'), assembly_tools_path %></td>
      <td><%= link_to t('.tool_management.barcode_generator', default: 'Barcode Generator'), new_barcode_generator_path %></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

<table class='table-menued'>
  <thead>
    <tr>
      <th colspan='5'><%= t('.masterdata.title', default: 'Master Data Maintenance') %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= link_to t('.masterdata.engine_model', default: 'Engine Model'), engine_models_path %></td>
      <td><%= link_to t('.masterdata.product_line', default: 'Product Line'), product_lines_path %></td>
      <td><%= link_to t('.masterdata.category', default: 'Category'), categories_path %></td>
      <td><%= link_to t('.masterdata.sub_category', default: 'SubCategory'), sub_categories_path %></td>
      <td><%= link_to t('.masterdata.facility_type', default: 'Facility Type'), facility_types_path %></td>
    </tr>
    <tr>
      <td><%= link_to t('.masterdata.manufacturer', default: 'Manufacturer'), manufacturers_path %></td>
      <td><%= link_to t('.masterdata.workshop_process', default: 'Workshop Process'), workshop_processes_path %></td>
      <td><%= link_to t('.masterdata.agency', default: 'Agency'), agencies_path %></td>
      <td><%= link_to t('.masterdata.setting_device', default: 'Setting Devices'), setting_devices_path %></td>
      <td><%= link_to t('.masterdata.setting_type', default: 'Setting Types'), setting_types_path %></td>
    </tr>
    <tr>
      <td><%= link_to t('.masterdata.facility_code', default: 'Facility Code'), facility_codes_path %></td>
      <td><%= link_to t('.masterdata.manufacturer', default: 'Manufacturer'), manufacturers_path %></td>
      <td><%= link_to t('.masterdata.sharpen_device', default: 'Sharpen Types'), sharpen_devices_path %></td>
      <td><%= link_to t('.masterdata.data_injection', default: 'Data Injection'), new_data_injection_path %></td>
      <td></td>
    </tr>
  </tbody>
</table>

<table class='table-menued'>
  <thead>
    <tr>
      <th colspan='5'><%= t('.access_control.title', default: 'Access Control Maintenance') %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= link_to t('.access_control.user', default: 'User'), users_path %></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>