config/routes.rb
Toolman::Application.routes.draw do

  resources :data_injections, :only => [:create, :new, :index, :show]

  resources :combination_tools

  resources :service_stock_orders, :except => [:new] do
    collection do
      get :new_in
      get :new_out
    end
  end

  resources :barcode_generators

  resources :tool_cards

  resources :quality_categories

  resources :quality_deviation_reports do
    member do
      put :confirm
    end
  end

  resources :scrap_orders do
  resources :items, :controller => :scrap_order_items
    member do
      put :confirm
    end
  end

  resources :scrap_types

  resources :tunning_work_orders do
    member do
      put :confirm
    end
    # resources :setting_items, :controller => :tunning_work_order_setting_items
    # resources :sharpen_items, :controller => :tunning_work_order_sharpen_items
  end

  resources :sharpen_devices

  resources :setting_types

  resources :setting_devices

  resources :assembly_tools do
    member do
      put :confirm
    end
    resources :items, :controller => :assembly_tool_items
    resources :tunning_work_orders
  end

  resources :tool_materials do
    member do
      get :print
    end
    resources :serving_parts do
      collection do 
        post :mass_create
        post :print
      end
    end
  end

  resources :agencies

  resources :manufacturers

  resources :sub_categories

  resources :workshop_processes

  resources :product_lines

  resources :engine_models
  
  resources :categories
  
  resources :facility_types
  
  resources :facility_codes

##############################################
  authenticated :user do
    root :to => 'home#index'
  end

  devise_for :users do
    root :to => 'devise/sessions#new'
  end
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users, :only => [:show, :index]
##############################################

end

app/models/assembly_tool_item.rb
class AssemblyToolItem < ActiveRecord::Base
  belongs_to :assembly_tool
  belongs_to :tool_material
  belongs_to :sharpen_device
  attr_accessible :quantity, :sharpen_time, :tool_material_id, :assembly_tool_id, :sharpen_device_id
  
  def to_str
    I18n.t('activerecord.attributes.assembly_tool_item.item_description',
           :quantity => quantity,
           :name => tool_material)
  end
  alias to_label to_str
  alias to_s to_str
end

app/controllers/assembly_tool_items_controller.rb
class AssemblyToolItemsController < ApplicationController
  before_filter :find_assembly_tool
  def index
    @assembly_tool_items = @assembly_tool.items.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assembly_tool_items }
    end
  end

  def show
    @assembly_tool_item = @assembly_tool.items.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @assembly_tool_item }
    end
  end

  def new
    @assembly_tool_item = @assembly_tool.items.build
    
    respond_to do |format|
      unless @assembly_tool.is_confirm
        @assembly_tool_item = @assembly_tool.items.build
        format.html # new.html.erb
        format.json { render json: @assembly_tool_item }
      else
        format.html {redirect_to assembly_tool_items_url(@assembly_tool), :notice => "Assembly Tool's confirmed."}
      end
    end
  end

  def edit
    @assembly_tool_item = @assembly_tool.items.find(params[:id])
  end

  def create
    @assembly_tool_item = @assembly_tool.items.new(params[:assembly_tool_item])
    respond_to do |format|
      if @assembly_tool_item.save
        format.html { redirect_to assembly_tool_item_url(@assembly_tool,@assembly_tool_item), notice: 'Assembly tool was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @assembly_tool_item = @assembly_tool.items.find(params[:id])
    respond_to do |format|
      if !@assembly_tool.is_confirm && @assembly_tool_item.update_attributes(params[:assembly_tool_item])
        format.html { redirect_to assembly_tool_items_url(@assembly_tool), notice: 'Assembly tool was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to edit_assembly_tool_item_url(@assembly_tool, @assembly_tool_item), :notice => "update fail!" }
        #format.html { render action: "edit",:notice => "update fail!" }
        format.json { render json: @assembly_tool_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @assembly_tool_item = @assembly_tool.items.find(params[:id])

    respond_to do |format|
      if !@assembly_tool.is_confirm && @assembly_tool_item.destroy
        format.html { redirect_to assembly_tool_items_url }
        format.json { head :no_content }
      else
        format.html { redirect_to assembly_tool_items_url, :notice => "destroy fail" }
      end
    end
  end

  protected

  def find_assembly_tool
    @assembly_tool = AssemblyTool.find(params[:assembly_tool_id])
  end
end

app/helpers/assembly_tool_items_helper.rb
module AssemblyToolItemsHelper
end

app/views/assembly_tool_items/_form.html.erb
<%= simple_form_for(@assembly_tool_item, :url =>( @assembly_tool_item.new_record? ? assembly_tool_items_path(@assembly_tool) : assembly_tool_item_path(@assembly_tool,@assembly_tool_item))  ) do |f| %>  
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :assembly_tool, disabled: true %>
    <%= f.association :tool_material %>
    <%= f.input :quantity %>
    <%= f.association :sharpen_device %>
    <%= f.input :sharpen_time %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/assembly_tool_items/edit.html.erb
<% content_for :breadcrumb do %>
  <li><%= link_to t('views.home.title', default: 'Home'), root_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%= link_to t('assembly_tools.index.title'), assembly_tools_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%= link_to t('assembly_tool_items.index.title'), assembly_tool_items_path(@tool_material) %></li>
  <li><span class='divider'>/</span></li>
  <li><%= t('.title') %></li>
<% end %>
<h1><%=t '.title'%></h1>

<%= render 'form' %>

<%= link_to t('helpers.links.show'), @assembly_tool_item, class: 'btn-show' %>
<%= link_to t('helpers.links.back'), assembly_tool_items_path(@assembly_tool), class: 'btn-back' %>

app/views/assembly_tool_items/index.html.erb
<%- model_class = AssemblyToolItem.new.class -%>
<% content_for :breadcrumb do %>
  <li><%= link_to t('views.home.title', default: 'Home'), root_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%=link_to t('assembly_tools.index.title'), assembly_tools_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%=t '.title', default: model_class.model_name.human.pluralize %></li>
<% end %>
<h1><%=t '.title', default: model_class.model_name.human.pluralize %></h1>    

<div class='operation-group'>
  <div class='action-group'>
    <%= link_to t('.new', default: t('helpers.links.new')), new_assembly_tool_item_path(@tool_material), class: 'btn-new' %>
  </div>
</div>

<table class='table-listed'>
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:assembly_tool) %></th>
      <th><%= model_class.human_attribute_name(:tool_material) %></th>
      <th><%= model_class.human_attribute_name(:quantity) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= t('.actions', default: t('helpers.actions')) %></th>
    </tr>
  </thead>
  <tbody>
    <% @assembly_tool_items.each do |assembly_tool_item| %>
      <tr>
        <td><%= assembly_tool_item.assembly_tool %></td>
        <td><%= assembly_tool_item.tool_material %></td>
        <td><%= assembly_tool_item.quantity %></td>
        <td><%= l(assembly_tool_item.created_at) %></td>
        <td><div class='btn-group'>
          <%= link_to t('.show', default: t('helpers.links.show')), assembly_tool_item_path(@assembly_tool, assembly_tool_item), class: 'btn-show' %>
          <%= link_to t('.edit', default: t('helpers.links.edit')), edit_assembly_tool_item_path(@assembly_tool, assembly_tool_item), class: 'btn-edit' %>
          <%= link_to t('.destroy', default: t('helpers.links.destroy')), assembly_tool_item_path(@assembly_tool, assembly_tool_item), confirm: t('.confirm', default: t('helpers.links.destroy_confirm', default: 'Are you sure?')), method: :delete, class: 'btn-destroy' %></div></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/assembly_tool_items/new.html.erb
<% content_for :breadcrumb do %>
  <li><%= link_to t('views.home.title', default: 'Home'), root_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%= link_to t('assembly_tools.index.title'), assembly_tools_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%= link_to t('assembly_tool_items.index.title'), assembly_tool_items_path(@assembly_tool) %></li>
  <li><span class='divider'>/</span></li>
  <li><%= t('.title') %></li>
<% end %>
<h1><%=t '.title'%></h1>

<%= render 'form' %>

<%= link_to t('helpers.links.back') , assembly_tool_items_path(@assembly_tool), class: 'btn-back' %>

app/views/assembly_tool_items/show.html.erb
<% content_for :breadcrumb do %>
  <li><%= link_to t('views.home.title', default: 'Home'), root_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%= link_to t('assembly_tools.index.title'), assembly_tools_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%= link_to t('assembly_tool_items.index.title'), assembly_tool_items_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%= t('.title') %></li>
<% end %>
<h1><%= t('.title') %></h1>
<p><b><%= @assembly_tool.class.human_attribute_name(:product_line) %>:</b><%= @assembly_tool.product_line %></p>
<p><b><%= @assembly_tool.class.human_attribute_name(:facility_type) %>:</b><%= @assembly_tool.facility_type %></p>
<p><b><%= @assembly_tool.class.human_attribute_name(:facility_code) %>:</b><%= @assembly_tool.facility_code %></p>
<p><b><%= @assembly_tool.class.human_attribute_name(:workshop_process) %>:</b><%= @assembly_tool.workshop_process %></p>
<p><b><%= @assembly_tool.class.human_attribute_name(:engine_models) %>:</b><%= raw li_engine_models(@assembly_tool) %></p>
<p><b><%= @assembly_tool.class.human_attribute_name(:hilt_no) %>:</b><%= @assembly_tool.hilt_no %></p>
<p><b><%= @assembly_tool.class.human_attribute_name(:processing_position) %>:</b><%= @assembly_tool.processing_position %></p>
<p><b><%= @assembly_tool.class.human_attribute_name(:processing_hole) %>:</b><%= @assembly_tool.processing_hole %></p>
<p><b><%= @assembly_tool_item.class.human_attribute_name(:tool_material) %>:</b><%= @assembly_tool_item.tool_material %></p>
<p><b><%= @assembly_tool_item.class.human_attribute_name(:quantity) %>:</b><%= @assembly_tool_item.quantity %></p>
<p><b><%= @assembly_tool_item.class.human_attribute_name(:uom) %>:</b><%= @assembly_tool_item.uom %></p>
<p><b><%= @assembly_tool_item.class.human_attribute_name(:standard_sharpen_time) %>:</b><%= @assembly_tool_item.standard_sharpen_time %></p>
<%= link_to t('helpers.links.edit'), edit_assembly_tool_item_path(@assembly_tool, @assembly_tool_item), class: 'btn-edit' %>
<%= link_to t('helpers.links.back'), assembly_tool_items_path(@assembly_tool), class: 'btn-back' %>