config/routes.rb
Toolman::Application.routes.draw do

  resources :data_injections, :only => [:create, :new, :index, :show]

  resources :combination_tools

  resources :service_stock_orders, :except => [:new] do
    collection do
      get :new_in
      get :new_out
    end
  end

  resources :barcode_generators

  resources :tool_cards

  resources :quality_categories

  resources :quality_deviation_reports do
    member do
      put :confirm
    end
  end

  resources :scrap_orders do
  resources :items, :controller => :scrap_order_items
    member do
      put :confirm
    end
  end

  resources :scrap_types

  resources :tunning_work_orders do
    member do
      put :confirm
    end
    # resources :setting_items, :controller => :tunning_work_order_setting_items
    # resources :sharpen_items, :controller => :tunning_work_order_sharpen_items
  end

  resources :sharpen_devices

  resources :setting_types

  resources :setting_devices

  resources :assembly_tools do
    member do
      put :confirm
    end
    resources :items, :controller => :assembly_tool_items
    resources :tunning_work_orders
  end

  resources :tool_materials do
    member do
      get :print
    end
    resources :serving_parts do
      collection do 
        post :mass_create
        post :print
      end
    end
  end

  resources :agencies

  resources :manufacturers

  resources :sub_categories

  resources :workshop_processes

  resources :product_lines

  resources :engine_models
  
  resources :categories
  
  resources :facility_types
  
  resources :facility_codes

##############################################
  authenticated :user do
    root :to => 'home#index'
  end

  devise_for :users do
    root :to => 'devise/sessions#new'
  end
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users, :only => [:show, :index]
##############################################

end

app/models/combination_tool.rb
class CombinationTool < ActiveRecord::Base
  STOCK_STATUS_ISSUE = 'O'
  STOCK_STATUS_RECEIVE = 'I'

  belongs_to :assembly_tool
  belongs_to :stock_in_operator, :class_name => :User
  belongs_to :stock_out_operator, :class_name => :User

  has_many :items, :class_name => :CombinationToolItem

  attr_accessible :stock_in_date, :stock_in_operator_id, :stock_out_date, :stock_out_operator_id, :stock_status, :assembly_tool_id, :hilt_no, :hilt_no_seq

  scope :issued, where(:stock_status => STOCK_STATUS_ISSUE)
  scope :received, where(:stock_status => STOCK_STATUS_RECEIVE)

  def setup_for_issue_with_hilt_no(params = {})
    return if params[:hilt_no].blank? || params[:hilt_no_seq].blank?
    self.hilt_no, self.hilt_no_seq = params[:hilt_no], params[:hilt_no_seq]
    self.assembly_tool = AssemblyTool.confirmed.find_by_hilt_no(hilt_no)
    self.stock_status = STOCK_STATUS_ISSUE
    self.assembly_tool.items.each do |ass_item|
      ass_item.quantity.times do 
        self.items.build(:tool_material_id => ass_item.tool_material.id,
                         :stock_status => STOCK_STATUS_ISSUE)
      end if ass_item.quantity > 0
    end if assembly_tool
  end
end

app/controllers/combination_tools_controller.rb
class CombinationToolsController < ApplicationController
  # GET /combination_tools
  # GET /combination_tools.json
  def index
    @combination_tools = CombinationTool.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @combination_tools }
    end
  end

  # GET /combination_tools/1
  # GET /combination_tools/1.json
  def show
    @combination_tool = CombinationTool.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @combination_tool }
    end
  end

  # GET /combination_tools/new
  # GET /combination_tools/new.json
  def new
    @combination_tool = CombinationTool.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @combination_tool }
    end
  end

  # GET /combination_tools/1/edit
  def edit
    @combination_tool = CombinationTool.find(params[:id])
  end

  # POST /combination_tools
  # POST /combination_tools.json
  def create
    @combination_tool = CombinationTool.new(params[:combination_tool])

    respond_to do |format|
      if @combination_tool.save
        format.html { redirect_to @combination_tool, notice: 'Combination tool was successfully created.' }
        format.json { render json: @combination_tool, status: :created, location: @combination_tool }
      else
        format.html { render action: "new" }
        format.json { render json: @combination_tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /combination_tools/1
  # PUT /combination_tools/1.json
  def update
    @combination_tool = CombinationTool.find(params[:id])

    respond_to do |format|
      if @combination_tool.update_attributes(params[:combination_tool])
        format.html { redirect_to @combination_tool, notice: 'Combination tool was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @combination_tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /combination_tools/1
  # DELETE /combination_tools/1.json
  def destroy
    @combination_tool = CombinationTool.find(params[:id])
    @combination_tool.destroy

    respond_to do |format|
      format.html { redirect_to combination_tools_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/combination_tools_helper.rb
module CombinationToolsHelper
end

app/views/combination_tools/_form.html.erb
<%= simple_form_for(@combination_tool, :html => { :class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :assembly_tool %>
    <%= f.input :stock_status %>
    <%= f.association :stock_out_operator %>
    <%= f.input :stock_out_date, :as => :date_picker %>
    <%= f.association :stock_in_operator %>
    <%= f.input :stock_in_date, :as => :date_picker %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/combination_tools/edit.html.erb
<% content_for :breadcrumb do %>
  <li><%= link_to t('views.home.title', default: 'Home'), root_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%= link_to t('manufacturers.index.title'), manufacturers_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%= t('.title') %></li>
<% end %>
<h1><%=t '.title'%></h1>

<%= render 'form' %>

<%= link_to t('helpers.links.show'), @manufacturer, class: 'btn-show' %>
<%= link_to t('helpers.links.back'), manufacturers_path, class: 'btn-back' %>

app/views/combination_tools/index.html.erb
<h1>Listing combination_tools</h1>

<table>
  <tr>
    <th>Assembly tool</th>
    <th>Stock status</th>
    <th>Stock out operator</th>
    <th>Stock out date</th>
    <th>Stock in operator</th>
    <th>Stock in date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @combination_tools.each do |combination_tool| %>
  <tr>
    <td><%= combination_tool.assembly_tool %></td>
    <td><%= combination_tool.stock_status %></td>
    <td><%= combination_tool.stock_out_operator %></td>
    <td><%= combination_tool.stock_out_date %></td>
    <td><%= combination_tool.stock_in_operator %></td>
    <td><%= combination_tool.stock_in_date %></td>
    <td><%= link_to 'Show', combination_tool %></td>
    <td><%= link_to 'Edit', edit_combination_tool_path(combination_tool) %></td>
    <td><%= link_to 'Destroy', combination_tool, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Combination tool', new_combination_tool_path %>

app/views/combination_tools/new.html.erb
<% content_for :breadcrumb do %>
  <li><%= link_to t('views.home.title', default: 'Home'), root_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%= link_to t('manufacturers.index.title'), manufacturers_path %></li>
  <li><span class='divider'>/</span></li>
  <li><%= t('.title') %></li>
<% end %>
<h1><%=t '.title'%></h1>

<%= render 'form' %>

<%= link_to t('helpers.links.back') , manufacturers_path, class: 'btn-back' %>

app/views/combination_tools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Assembly tool:</b>
  <%= @combination_tool.assembly_tool %>
</p>

<p>
  <b>Stock status:</b>
  <%= @combination_tool.stock_status %>
</p>

<p>
  <b>Stock out operator:</b>
  <%= @combination_tool.stock_out_operator %>
</p>

<p>
  <b>Stock out date:</b>
  <%= @combination_tool.stock_out_date %>
</p>

<p>
  <b>Stock in operator:</b>
  <%= @combination_tool.stock_in_operator %>
</p>

<p>
  <b>Stock in date:</b>
  <%= @combination_tool.stock_in_date %>
</p>


<%= link_to 'Edit', edit_combination_tool_path(@combination_tool) %> |
<%= link_to 'Back', combination_tools_path %>